<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\CommonLibrary\FileProcessing.Core.CommonLibrary\FileProcessing.Core.CommonLibrary.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\ApiRateLimiter\FileProcessing.Infrastructure.ApiRateLimiter\FileProcessing.Infrastructure.ApiRateLimiter.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\BackgroundJobs\FileProcessing.Infrastructure.Background\FileProcessing.Infrastructure.Background.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Cache\FileProcessing.Infrastructure.Cache\FileProcessing.Infrastructure.Cache.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Email\FileProcessing.Infrastructure.Email\FileProcessing.Infrastructure.Email.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\TaskQueue\FileProcessing.Infrastructure.TaskQueue\FileProcessing.Infrastructure.TaskQueue.csproj" />
    <ProjectReference Include="..\..\..\Modules\UserManagement\UserManagement.PL\UserManagement.PL.csproj" />
   
  </ItemGroup>

</Project>
